name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create extension ZIP
        run: |
          zip -r nodetree_anim-${{ github.ref_name }}.zip . \
            -x ".git/*" \
               ".github/*" \
               ".DS_Store" \
               "__MACOSX/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: nodetree_anim-${{ github.ref_name }}.zip
          generate_release_notes: true
          body_path: release_notes/${{ github.ref_name }}.md
